### ISSUE TITLE
OverrideCallsSuper is too aggressive

### ISSUE THREAD

**Issue by BiggA94** [a-tarasyuk/eslint-plugin-resub#3]
Currently, overrideCallsSuper test for any function, that is called like the Lifecycle method, eg. 'componentDidMount'.

Now I want to create a React.Component, or React.PureComponent, beacuse there is no State.
The Problem here is, that all Lifecycle Methods are typed as possibly undefined:

``` typescript
    interface ComponentLifecycle<P, S, SS = any> extends NewLifecycle<P, S, SS>, DeprecatedLifecycle<P, S> {
        componentDidMount?(): void;
        shouldComponentUpdate?(nextProps: Readonly<P>, nextState: Readonly<S>, nextContext: any): boolean;
        componentWillUnmount?(): void;
        componentDidCatch?(error: Error, errorInfo: ErrorInfo): void;
    }
```

This leads to Type errors, if on tries to use them by e.g. calling `super.componentDidMount()`.

Suggestion:
Aply rule only to Classes, that extend ComponentBase.

**Comment by a-tarasyuk** [comment]
Fixed in 0.2.0
